[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://blogforgeai-production.up.railway.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200